GITHUB_URL = "https://github.com/didacdev"
LINKEDIN_URL = "https://www.linkedin.com/in/diego-sanchez-escribano/"
MAIL = "diego.sanchez.escribano@pm.me"
STAR_WARS_GITHUB_URL = "https://github.com/didacdev/Star-Wars-Encyclopedia"
STAR_WARS_TEXT = """
Aplicación de la Enciclopedia de Star Wars desarrollada en Swift utilizando SwiftUI. Utiliza la API de Star Wars (SWAPI) para obtener y mostrar información sobre los personajes de la saga Star Wars.
"""
CONNECT_FOUR_GITHUB_URL = "https://github.com/didacdev/Connect-Four"
CONNECT_FOUR_TEXT = """
Juego "Conecta Cuatro" para jugar en un solo dispositivo, donde los dos jgadores tendrán que turnarse para colocar las fichas en un tablero 7x6. El primer jugador que consiga poner cuatro fichas en una columna gana.
"""
WEB_GITHUB_URL = "https://github.com/didacdev/didacdev_web"
UAM_URL = "https://uam.es/CentroEstudiosPosgrado/MU_Formacion_Profesorado_Educacion_Secundaria_Bachillerato/1446794562391.htm?language=es_ES&nDept=5&pid=1446755975574&pidDept=1446823902965"
RCSMM_URL = "https://rcsmm.eu"
CSKG_URL = "https://katarinagurska.com/curso-of/interpretacion/interpretacion-itinerario-a/"
UNED_URL = "http://portal.uned.es/portal/page?_pageid=93,71802397&_dad=portal&_schema=PORTAL"
MBL_URL = "https://www.musicboxlearning.com"
TEMPO_URL = "https://www.tempomusical.es"
NUTRICYNN_URL = "https://www.nutricynn.com"
C1_URL = "https://www.cambridgeenglish.org/es/exams-and-tests/advanced/"
